[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m application.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONUNBUFFERED = "1"
PYTHONIOENCODING = "utf-8"