def agents():
    return [
        "Astra",
        "Breach",
        "Brimstone",
        "Chamber",
        "Cypher",
        "Fade",
        "Gekko",
        "Harbon",
        "Jett",
        "KAYO",
        "Killjoy",
        "Neon",
        "Omen",
        "Phoenix",
        "Raze",
        "Reyna",
        "Sage",
        "Skye",
        "Sova",
        "Viper",
        "Yoru",
    ]
