name: Deploy to ShardCloud (prod)

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar e Verificar ZIP do projeto
        run: |
          # exclua pasta .git e artefatos locais
          zip -r project.zip . -x ".git/*" -x ".github/*" -x "venv/*" -x "__pycache__/*"
          
          echo "Verificando o arquivo ZIP criado:"
          ls -lh project.zip

      - name: Fazer upload para ShardCloud
        env:
          SHARDCLOUD_TOKEN: ${{ secrets.SHARDCLOUD_TOKEN }}
          SHARDCLOUD_APP_ID: ${{ secrets.SHARDCLOUD_APP_ID }}
        run: |
          echo "Enviando ZIP para ShardCloud..."
          curl --show-error --silent \
            -X PUT "https://shardcloud.app/api/apps/${SHARDCLOUD_APP_ID}/file" \
            -H "Authorization: Bearer ${SHARDCLOUD_TOKEN}" \
            -F project=@project.zip \
            -o response.json -w "\nHTTP_STATUS:%{http_code}\n"
          
          echo "--- Início da Resposta da API ---"
          cat response.json
          echo "\n--- Fim da Resposta da API ---"

          STATUS_CODE=$(grep 'HTTP_STATUS' <<< "$(cat response.json)$(echo)" | tail -n 1 | cut -d: -f2)
          if [[ -z "$STATUS_CODE" || "$STATUS_CODE" -ge 400 ]]; then
            exit 1
          fi