name: Deploy to Shardcloud

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Shardcloud
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          https://shardcloud.app/api/github/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTk3MjEyMjV9.V0YvbsNDUY0lZbmNHWjAgfV9b6bWwwcqL6PkVEb7834
